//
// Created by 22343 on 2021/2/27.
//

#ifndef MYSOCKS_EXCEPTION_H
#define MYSOCKS_EXCEPTION_H

#define SERVER_SOCKET_CREATE_ERROR -1
#define SERVER_SOCKET_BIND_ERROR -2
#define SERVER_SOCKET_LISTEN_ERROR -3


#endif //MYSOCKS_EXCEPTION_H
